on: [push, pull_request]

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-22.04
    name: pogo on Elixir ${{matrix.elixir}} (OTP ${{matrix.otp}})
    strategy:
      matrix:
        otp: ['22.3', '23.3', '24.3', '25.2']
        elixir: ['1.11.4', '1.12.3', '1.13.4', '1.14.3']
        exclude:
          - otp: '22.3'
            elixir: '1.14.3'
          - otp: '25.2'
            elixir: '1.11.4'
          - otp: '25.2'
            elixir: '1.12.3'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted --dry-run
      - run: mix credo --strict -a
      - run: mix test --warnings-as-errors
      - run: mix dialyzer --halt-exit-status
